version: '3.4'

services:
  employeedailycheckin:
    image: employeedailycheckin
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
